import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import api from "../services/api";

function Reviews() {
    const [reviews, setReviews] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");

    const [search, setSearch] = useState("");
    const [statusFilter, setStatusFilter] = useState("all");
    const [scoreFilter, setScoreFilter] = useState("all");

    useEffect(() => {
        const loadReviews = async () => {
            try {
                setLoading(true);
                setError("");

                const response = await api.get("reviews/");

                console.log("Reviews:", response.data);

                setReviews(response.data);
            } catch (err) {
                console.error("Failed to load reviews:", err);

                setError(
                    "Unable to load reviews. Make sure the Django server is running."
                );
            } finally {
                setLoading(false);
            }
        };

        loadReviews();
    }, []);

    const filteredReviews = useMemo(() => {
        return reviews.filter((review) => {
            const searchText = search.toLowerCase().trim();

            const matchesSearch =
                !searchText ||
                review.pull_request_title
                    ?.toLowerCase()
                    .includes(searchText) ||
                String(review.pull_request).includes(searchText);

            const matchesStatus =
                statusFilter === "all" ||
                review.status === statusFilter;

            const score = Number(review.score);

            let matchesScore = true;

            if (scoreFilter === "high") {
                matchesScore = score >= 7;
            }

            if (scoreFilter === "medium") {
                matchesScore = score >= 4 && score < 7;
            }

            if (scoreFilter === "low") {
                matchesScore = score < 4;
            }

            return (
                matchesSearch &&
                matchesStatus &&
                matchesScore
            );
        });
    }, [reviews, search, statusFilter, scoreFilter]);

    const completedCount = reviews.filter(
        (review) => review.status === "completed"
    ).length;

    const processingCount = reviews.filter(
        (review) =>
            review.status === "processing" ||
            review.status === "pending"
    ).length;

    const failedCount = reviews.filter(
        (review) => review.status === "failed"
    ).length;

    const getScoreClass = (score) => {
        if (score >= 7) return "score-good";
        if (score >= 4) return "score-warning";
        return "score-danger";
    };

    const getStatusClass = (status) => {
        if (status === "completed") {
            return "status-completed";
        }

        if (
            status === "processing" ||
            status === "pending"
        ) {
            return "status-processing";
        }

        if (status === "failed") {
            return "status-failed";
        }

        return "";
    };

    const getFindingCount = (review) => {
        if (Array.isArray(review.findings)) {
            return review.findings.length;
        }

        if (typeof review.finding_count === "number") {
            return review.finding_count;
        }

        return 0;
    };

    const getStatusLabel = (status) => {
        if (status === "completed") return "Completed";
        if (status === "processing") return "Processing";
        if (status === "pending") return "Pending";
        if (status === "failed") return "Failed";

        return status || "Unknown";
    };

    if (loading) {
        return (
            <div className="page-container">
                <div className="loading-state">
                    <div className="loading-spinner"></div>
                    <h2>Loading AI reviews...</h2>
                    <p>
                        Retrieving review results from the Django API.
                    </p>
                </div>
            </div>
        );
    }

    if (error) {
        return (
            <div className="page-container">
                <div className="page-header">
                    <div>
                        <h1>AI Reviews</h1>
                        <p>
                            Review results generated by the AI
                            code analysis system.
                        </p>
                    </div>
                </div>

                <div className="error-state">
                    <h2>Unable to load reviews</h2>
                    <p>{error}</p>
                </div>
            </div>
        );
    }

    return (
        <div className="page-container">

            {/* Page Header */}

            <div className="page-header">

                <div>
                    <h1>AI Reviews</h1>

                    <p>
                        Review results generated by the AI
                        code analysis system.
                    </p>
                </div>

                <div className="review-count">
                    {reviews.length} total reviews
                </div>

            </div>


            {/* Review Statistics */}

            <div className="review-summary-grid">

                <div className="review-summary-card">

                    <div className="review-summary-icon">
                        ✦
                    </div>

                    <div>
                        <span>Total Reviews</span>
                        <strong>{reviews.length}</strong>
                    </div>

                </div>


                <div className="review-summary-card">

                    <div className="review-summary-icon">
                        ✓
                    </div>

                    <div>
                        <span>Completed</span>
                        <strong>{completedCount}</strong>
                    </div>

                </div>


                <div className="review-summary-card">

                    <div className="review-summary-icon">
                        ◷
                    </div>

                    <div>
                        <span>Processing</span>
                        <strong>{processingCount}</strong>
                    </div>

                </div>


                <div className="review-summary-card">

                    <div className="review-summary-icon">
                        !
                    </div>

                    <div>
                        <span>Failed</span>
                        <strong>{failedCount}</strong>
                    </div>

                </div>

            </div>


            {/* Filters */}

            <div className="review-filters">

                <div className="search-box">

                    <input
                        type="text"
                        placeholder="Search by pull request..."
                        value={search}
                        onChange={(event) =>
                            setSearch(event.target.value)
                        }
                    />

                </div>


                <select
                    value={statusFilter}
                    onChange={(event) =>
                        setStatusFilter(event.target.value)
                    }
                >
                    <option value="all">
                        All statuses
                    </option>

                    <option value="completed">
                        Completed
                    </option>

                    <option value="processing">
                        Processing
                    </option>

                    <option value="pending">
                        Pending
                    </option>

                    <option value="failed">
                        Failed
                    </option>

                </select>


                <select
                    value={scoreFilter}
                    onChange={(event) =>
                        setScoreFilter(event.target.value)
                    }
                >
                    <option value="all">
                        All scores
                    </option>

                    <option value="high">
                        High score (7–10)
                    </option>

                    <option value="medium">
                        Medium score (4–6)
                    </option>

                    <option value="low">
                        Low score (0–3)
                    </option>

                </select>

            </div>


            {/* Result Count */}

            <div className="reviews-result-count">

                Showing{" "}
                <strong>{filteredReviews.length}</strong>{" "}
                of{" "}
                <strong>{reviews.length}</strong>{" "}
                reviews

            </div>


            {/* Review List */}

            {filteredReviews.length === 0 ? (

                <div className="empty-state">

                    <div className="empty-state-icon">
                        ✦
                    </div>

                    <h2>No reviews found</h2>

                    <p>
                        No reviews match your current search
                        or filters.
                    </p>

                </div>

            ) : (

                <div className="reviews-list">

                    {filteredReviews.map((review) => {

                        const score = Number(review.score);
                        const findingCount = getFindingCount(review);

                        return (
                            <article
                                className="review-card"
                                key={review.id}
                            >

                                <div className="review-card-main">


                                    {/* Review Identity */}

                                    <div className="review-card-title">

                                        <span className="review-id">
                                            Review #{review.id}
                                        </span>

                                        <h2>
                                            PR #
                                            {review.pull_request}
                                        </h2>

                                        <p>
                                            {review.pull_request_title ||
                                                "Untitled pull request"}
                                        </p>

                                    </div>


                                    {/* Status */}

                                    <div className="review-card-status">

                                        <span
                                            className={`status-badge ${getStatusClass(
                                                review.status
                                            )}`}
                                        >
                                            {getStatusLabel(
                                                review.status
                                            )}
                                        </span>

                                    </div>


                                    {/* Score */}

                                    <div
                                        className={`review-card-score ${getScoreClass(
                                            score
                                        )}`}
                                    >

                                        <span>
                                            AI Score
                                        </span>

                                        <strong>
                                            {review.score ?? "—"}
                                            <small>/10</small>
                                        </strong>

                                    </div>


                                                                        {/* Findings */}
                                    <div className="review-card-findings">
                                        <span>Findings</span>

                                        <strong>{getFindingCount(review)}</strong>

                                        <div className="finding-breakdown">
                                            <span className="finding-count critical">
                                                {review.critical_count || 0} Critical
                                            </span>

                                            <span className="finding-count high">
                                                {review.high_count || 0} High
                                            </span>

                                            <span className="finding-count medium">
                                                {review.medium_count || 0} Medium
                                            </span>

                                            <span className="finding-count low">
                                                {review.low_count || 0} Low
                                            </span>
                                        </div>
                                    </div>


                                    {/* Date */}

                                    <div className="review-card-date">

                                        <span>
                                            Created
                                        </span>

                                        <strong>
                                            {review.created_at
                                                ? new Date(
                                                      review.created_at
                                                  ).toLocaleString()
                                                : "—"}
                                        </strong>

                                    </div>

                                </div>


                                {/* Footer */}

                                <div className="review-card-footer">

                                    <span>
                                        AI-generated code analysis
                                    </span>

                                    <Link
                                        to={`/reviews/${review.id}`}
                                        className="view-review-button"
                                    >
                                        View Review →
                                    </Link>

                                </div>

                            </article>
                        );
                    })}

                </div>

            )}

        </div>
    );
}

export default Reviews;